apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "51.0.0" # Adjust version based on Helm chart repo
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "cloudflare-tunnel"
        hosts:
          - host: grafana.blurer.net
            paths:
              - path: /
                pathType: ImplementationSpecific
      adminPassword: admin
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "cloudflare-tunnel"
        hosts:
          - host: prometheus.blurer.net
            paths:
              - path: /
                pathType: ImplementationSpecific
