apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
  values:
    grafana:
      adminpassword: bryanlurer
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "cloudflare-tunnel"
        hosts:
          - host: grafana.blurer.net
            paths:
              - path: /
                pathType: ImplementationSpecific
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "cloudflare-tunnel"
        hosts:
          - host: prometheus.blurer.net
            paths:
              - path: /
                pathType: ImplementationSpecific
