apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cloudflared-tunnel
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials
      - name: config
        configMap:
          name: cloudflared-config
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: monitoring
data:
  config.yaml: |
    tunnel: <your-tunnel-id>
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: grafana.blurer.net
        service: http://grafana:3000
      - hostname: prometheus.blurer.net
        service: http://prometheus:9090
      - service: http_status:404
